import { useState, useEffect, useCallback } from 'react';
import jsPDF from 'jspdf';
import { PageContainer } from '../components/layout/Layout';
import { PageLoader } from '../components/ui/LoadingSpinner';
import api from '../services/api';
import { useT } from '../i18n/translations';
import { useToastStore } from '../store/toastStore';

const fmt = (n: number) => `LKR ${Number(n).toFixed(2)}`;
const today = new Date().toISOString().slice(0, 10);
const firstOfMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10);

// ── Shared PDF helpers ────────────────────────────────────────────────────────
const SHOP_NAME    = 'Kalanai Graphics & Print Solutions';
const SHOP_ADDRESS = '612/2/A, Kandy Road, Eldeniya, Kadawatha';
const SHOP_PHONE   = '0112 927 635 | 0706 812 220';
type RGB = [number, number, number];
const C: Record<string, RGB> = {
  navy:   [13,  37,  76],
  blue:   [30,  100, 220],
  even:   [244, 247, 252],
  border: [200, 212, 230],
  text:   [20,  30,  50],
  muted:  [100, 115, 140],
  steel:  [160, 185, 220],
  white:  [255, 255, 255],
  green:  [22,  140, 70],
  red:    [200, 40,  40],
};

function makePDF() {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });
  const W = 210, ML = 14, MR = 14, CW = W - ML - MR;
  const fill   = (c: RGB) => doc.setFillColor(c[0], c[1], c[2]);
  const ink    = (c: RGB) => doc.setTextColor(c[0], c[1], c[2]);
  const stroke = (c: RGB) => doc.setDrawColor(c[0], c[1], c[2]);
  const bold   = () => doc.setFont('helvetica', 'bold');
  const normal = () => doc.setFont('helvetica', 'normal');
  const sz     = (s: number) => doc.setFontSize(s);

  const header = (badge: string) => {
    fill(C.navy); doc.rect(0, 0, W, 42, 'F');
    fill(C.blue); doc.rect(W - 6, 0, 6, 42, 'F');
    bold(); sz(17); ink(C.white); doc.text(SHOP_NAME, ML, 16);
    normal(); sz(8.5); ink(C.steel);
    doc.text(SHOP_ADDRESS, ML, 24);
    doc.text(SHOP_PHONE, ML, 30.5);
    fill(C.blue); doc.rect(W - 62, 8, 50, 16, 'F');
    bold(); sz(10); ink(C.white); doc.text(badge, W - 37, 19, { align: 'center' });
    fill(C.blue); doc.rect(0, 42, W - 6, 1.5, 'F');
  };

  const hline = (y: number, lw = 0.3) => {
    stroke(C.border); doc.setLineWidth(lw); doc.line(ML, y, W - MR, y);
  };

  const footer = () => {
    const FY = 277;
    fill(C.navy); doc.rect(0, FY - 3, W, 23, 'F');
    fill(C.blue); doc.rect(0, FY - 3, W, 1.5, 'F');
    bold(); sz(9); ink(C.white);
    doc.text(`Generated by ${SHOP_NAME}`, W / 2, FY + 5, { align: 'center' });
    normal(); sz(7.5); ink(C.steel);
    doc.text(`${SHOP_ADDRESS} | ${SHOP_PHONE}`, W / 2, FY + 11, { align: 'center' });
    doc.text(`Printed: ${new Date().toLocaleString()}`, W / 2, FY + 16, { align: 'center' });
  };

  return { doc, W, ML, MR, CW, fill, ink, stroke, bold, normal, sz, header, hline, footer };
}

// ── Sales Report PDF ──────────────────────────────────────────────────────────
function downloadSalesPDF(
  salesData: { periods: unknown[]; summary: Record<string, number> },
  dateFrom: string,
  dateTo: string
) {
  const { doc, W, ML, MR, fill, ink, bold, normal, sz, header, hline, footer } = makePDF();
  const CW = W - ML - MR;

  header('SALES REPORT');

  // Date range
  const rangeY = 50;
  bold(); sz(8); ink(C.muted); doc.text('REPORT PERIOD', ML, rangeY);
  bold(); sz(11); ink(C.navy);
  const df = new Date(dateFrom).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const dt = new Date(dateTo).toLocaleDateString('en-GB',   { day: '2-digit', month: 'short', year: 'numeric' });
  doc.text(`${df}  →  ${dt}`, ML, rangeY + 7);
  hline(rangeY + 14, 0.5);

  // Summary boxes
  const sumY = rangeY + 20;
  const BOX_W = (CW - 9) / 4;
  const summary = salesData.summary || {};
  const boxes = [
    { label: 'TOTAL REVENUE',   value: fmt(Number(summary.total_revenue   || 0)), color: C.blue  },
    { label: 'TOTAL PROFIT',    value: fmt(Number(summary.total_profit     || 0)), color: C.green },
    { label: 'TRANSACTIONS',    value: String(summary.total_transactions   || 0),  color: C.navy  },
    { label: 'TOTAL DISCOUNTS', value: fmt(Number(summary.total_discounts  || 0)), color: C.red   },
  ];
  boxes.forEach((b, i) => {
    const bx = ML + i * (BOX_W + 3);
    fill(C.even); doc.rect(bx, sumY, BOX_W, 20, 'F');
    normal(); sz(7); ink(C.muted); doc.text(b.label, bx + BOX_W / 2, sumY + 7, { align: 'center' });
    bold(); sz(10); ink(b.color); doc.text(b.value, bx + BOX_W / 2, sumY + 15, { align: 'center' });
  });

  // Table
  const TBL_Y = sumY + 26;
  const ROW_H = 8;
  const COL = { date: ML, txn: ML + 60, rev: ML + 95, profit: ML + 135, disc: W - MR };

  fill(C.navy); doc.rect(ML, TBL_Y, CW, 9, 'F');
  bold(); sz(8); ink(C.white);
  doc.text('DATE',         COL.date,   TBL_Y + 6);
  doc.text('TRANSACTIONS', COL.txn,    TBL_Y + 6, { align: 'center' });
  doc.text('REVENUE',      COL.rev,    TBL_Y + 6, { align: 'right' });
  doc.text('PROFIT',       COL.profit, TBL_Y + 6, { align: 'right' });
  doc.text('DISCOUNTS',    COL.disc,   TBL_Y + 6, { align: 'right' });

  let rowY = TBL_Y + 9;
  normal(); sz(8.5);
  (salesData.periods as Array<Record<string, unknown>>).forEach((row, idx) => {
    if (idx % 2 === 0) { fill(C.even); doc.rect(ML, rowY, CW, ROW_H, 'F'); }
    ink(C.text);
    doc.text(new Date(String(row.period)).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }), COL.date, rowY + 5.5);
    doc.text(String(row.transactions), COL.txn, rowY + 5.5, { align: 'center' });
    bold(); ink(C.blue);  doc.text(fmt(Number(row.revenue)),   COL.rev,    rowY + 5.5, { align: 'right' });
    ink(C.green);         doc.text(fmt(Number(row.profit)),    COL.profit, rowY + 5.5, { align: 'right' });
    normal(); ink(C.red); doc.text(fmt(Number(row.discounts)), COL.disc,   rowY + 5.5, { align: 'right' });
    rowY += ROW_H;
  });

  footer();
  doc.save(`Sales-Report-${dateFrom}-to-${dateTo}.pdf`);
}

// ── Print Shop Usage PDF ──────────────────────────────────────────────────────
function downloadPrintShopPDF(
  records: Array<Record<string, unknown>>,
  dateFrom: string,
  dateTo: string
) {
  const { doc, W, ML, MR, fill, ink, bold, normal, sz, header, hline, footer } = makePDF();
  const CW = W - ML - MR;

  header('PRINT SHOP\nUSAGE');

  const rangeY = 50;
  bold(); sz(8); ink(C.muted); doc.text('REPORT PERIOD', ML, rangeY);
  bold(); sz(11); ink(C.navy);
  const df = new Date(dateFrom).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const dt = new Date(dateTo).toLocaleDateString('en-GB',   { day: '2-digit', month: 'short', year: 'numeric' });
  doc.text(`${df}  →  ${dt}`, ML, rangeY + 7);

  const totalCost = records.reduce((s, r) => s + Number(r.total_cost || 0), 0);
  bold(); sz(8); ink(C.muted); doc.text('TOTAL COST', W - MR, rangeY, { align: 'right' });
  bold(); sz(14); ink(C.navy); doc.text(fmt(totalCost), W - MR, rangeY + 9, { align: 'right' });
  hline(rangeY + 16, 0.5);

  const TBL_Y = rangeY + 22;
  const ROW_H = 8;
  const COL = { ref: ML, purpose: ML + 40, cost: ML + 130, by: ML + 155, date: W - MR };

  fill(C.navy); doc.rect(ML, TBL_Y, CW, 9, 'F');
  bold(); sz(8); ink(C.white);
  doc.text('REFERENCE',  COL.ref,     TBL_Y + 6);
  doc.text('PURPOSE',    COL.purpose, TBL_Y + 6);
  doc.text('COST',       COL.cost,    TBL_Y + 6, { align: 'right' });
  doc.text('BY',         COL.by,      TBL_Y + 6);
  doc.text('DATE',       COL.date,    TBL_Y + 6, { align: 'right' });

  let rowY = TBL_Y + 9;
  normal(); sz(8.5);
  records.forEach((rec, idx) => {
    if (idx % 2 === 0) { fill(C.even); doc.rect(ML, rowY, CW, ROW_H, 'F'); }
    ink(C.blue);  bold(); doc.text(String(rec.reference_number || ''), COL.ref, rowY + 5.5);
    normal(); ink(C.text);
    const purpose = String(rec.purpose || '—');
    doc.text(purpose.length > 30 ? purpose.slice(0, 28) + '..' : purpose, COL.purpose, rowY + 5.5);
    bold(); ink(C.navy); doc.text(fmt(Number(rec.total_cost || 0)), COL.cost, rowY + 5.5, { align: 'right' });
    normal(); ink(C.muted);
    doc.text(String(rec.created_by_name || ''), COL.by, rowY + 5.5);
    doc.text(new Date(String(rec.created_at)).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }), COL.date, rowY + 5.5, { align: 'right' });
    rowY += ROW_H;
  });

  // Total row
  rowY += 2;
  fill(C.navy); doc.rect(ML, rowY, CW, 10, 'F');
  bold(); sz(9); ink(C.white);
  doc.text('TOTAL', COL.purpose, rowY + 7);
  doc.text(fmt(totalCost), COL.cost, rowY + 7, { align: 'right' });

  footer();
  doc.save(`PrintShop-Usage-${dateFrom}-to-${dateTo}.pdf`);
}

// ── Print Shop Detailed PDF (items per record) ────────────────────────────────
interface DetailedRecord {
  id: number;
  reference_number: string;
  purpose?: string;
  notes?: string;
  total_cost: number;
  created_by_name: string;
  created_at: string;
  items: Array<{
    id: number;
    product_name: string;
    quantity: number;
    cost_price: number;
    subtotal: number;
  }>;
}

function downloadDetailedPrintShopPDF(
  records: DetailedRecord[],
  dateFrom: string,
  dateTo: string
) {
  const { doc, W, ML, MR, fill, ink, bold, normal, sz, header, hline, footer } = makePDF();
  const CW = W - ML - MR;
  const PAGE_BOTTOM = 268;

  const addPage = () => {
    footer();
    doc.addPage();
    header('PRINT SHOP\nUSAGE');
    return 52;
  };

  header('PRINT SHOP\nUSAGE');

  // Date range + grand total
  const rangeY = 50;
  bold(); sz(8); ink(C.muted); doc.text('REPORT PERIOD', ML, rangeY);
  bold(); sz(11); ink(C.navy);
  const df = new Date(dateFrom).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const dt = new Date(dateTo).toLocaleDateString('en-GB',   { day: '2-digit', month: 'short', year: 'numeric' });
  doc.text(`${df}  →  ${dt}`, ML, rangeY + 7);
  const grandTotal = records.reduce((s, r) => s + Number(r.total_cost || 0), 0);
  bold(); sz(8); ink(C.muted); doc.text('GRAND TOTAL', W - MR, rangeY, { align: 'right' });
  bold(); sz(14); ink(C.navy); doc.text(fmt(grandTotal), W - MR, rangeY + 9, { align: 'right' });
  hline(rangeY + 16, 0.5);

  let y = rangeY + 22;

  for (const rec of records) {
    const itemCount = rec.items?.length || 0;
    // Estimate height needed: header(10) + col header(7) + items(8 each) + total(9) + gap(5)
    const neededH = 10 + 7 + itemCount * 8 + 9 + 5;
    if (y + neededH > PAGE_BOTTOM) { y = addPage(); }

    // Record header bar
    fill(C.navy); doc.rect(ML, y, CW, 10, 'F');
    bold(); sz(8.5); ink(C.white);
    const refStr = String(rec.reference_number);
    const purStr = rec.purpose ? (rec.purpose.length > 35 ? rec.purpose.slice(0, 33) + '..' : rec.purpose) : '—';
    const dateStr = new Date(rec.created_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
    doc.text(refStr,                               ML + 2,        y + 7);
    doc.text(purStr,                               ML + 42,       y + 7);
    normal(); sz(7.5); ink(C.steel);
    doc.text(`by ${rec.created_by_name}`,          ML + 130,      y + 7);
    bold(); sz(8); ink(C.white);
    doc.text(dateStr,                              W - MR,        y + 7, { align: 'right' });
    y += 10;

    // Column headers for items
    fill(C.even); doc.rect(ML, y, CW, 7, 'F');
    normal(); sz(7.5); ink(C.muted);
    doc.text('PRODUCT',   ML + 3,     y + 5);
    doc.text('QTY',       ML + 110,   y + 5, { align: 'right' });
    doc.text('UNIT COST', ML + 140,   y + 5, { align: 'right' });
    doc.text('SUBTOTAL',  W - MR,     y + 5, { align: 'right' });
    y += 7;

    // Items
    for (const item of (rec.items || [])) {
      if (y + 8 > PAGE_BOTTOM) { y = addPage(); }
      normal(); sz(8.5); ink(C.text);
      bold(); doc.text(String(item.product_name), ML + 3, y + 5.5);
      normal();
      doc.text(Number(item.quantity).toFixed(3),   ML + 110, y + 5.5, { align: 'right' });
      ink(C.muted); doc.text(fmt(Number(item.cost_price)), ML + 140, y + 5.5, { align: 'right' });
      bold(); ink(C.navy); doc.text(fmt(Number(item.subtotal)), W - MR, y + 5.5, { align: 'right' });
      y += 8;
    }

    // Record total row
    fill([230, 237, 250] as RGB); doc.rect(ML, y, CW, 9, 'F');
    bold(); sz(8.5); ink(C.navy);
    doc.text('Record Total', ML + 3, y + 6.5);
    doc.text(fmt(Number(rec.total_cost)), W - MR, y + 6.5, { align: 'right' });
    y += 13;
  }

  footer();
  doc.save(`PrintShop-Detailed-${dateFrom}-to-${dateTo}.pdf`);
}

// ── Report Tab types ──────────────────────────────────────────────────────────
type ReportTab = 'sales' | 'products' | 'inventory' | 'cashiers' | 'printshop';

export default function Reports() {
  const t = useT();
  const toast = useToastStore();
  const [tab, setTab] = useState<ReportTab>('sales');
  const [dateFrom, setDateFrom] = useState(firstOfMonth);
  const [dateTo, setDateTo] = useState(today);
  const [loading, setLoading] = useState(false);
  const [salesData, setSalesData] = useState<{ periods: unknown[]; summary: Record<string, number> } | null>(null);
  const [productsData, setProductsData] = useState<unknown[]>([]);
  const [inventoryData, setInventoryData] = useState<unknown[]>([]);
  const [cashiersData, setCashiersData] = useState<unknown[]>([]);
  const [printshopData, setPrintshopData] = useState<Array<Record<string, unknown>>>([]);
  const [generatingPDF, setGeneratingPDF] = useState(false);

  const handleDetailedPDF = async () => {
    if (!printshopData.length) return;
    setGeneratingPDF(true);
    try {
      const detailed = await Promise.all(
        printshopData.map(r => api.get(`/internal-use/${r.id}`).then(res => res.data.data))
      );
      downloadDetailedPrintShopPDF(detailed as DetailedRecord[], dateFrom, dateTo);
    } catch {
      toast.error('Failed to generate detailed PDF');
    } finally { setGeneratingPDF(false); }
  };

  const load = useCallback(async () => {
    setLoading(true);
    try {
      if (tab === 'sales') {
        const r = await api.get(`/reports/sales?date_from=${dateFrom}&date_to=${dateTo}`);
        setSalesData(r.data.data);
      } else if (tab === 'products') {
        const r = await api.get(`/reports/product-sales?date_from=${dateFrom}&date_to=${dateTo}`);
        setProductsData(r.data.data);
      } else if (tab === 'inventory') {
        const r = await api.get('/reports/inventory');
        setInventoryData(r.data.data);
      } else if (tab === 'cashiers') {
        const r = await api.get(`/reports/cashiers?date_from=${dateFrom}&date_to=${dateTo}`);
        setCashiersData(r.data.data);
      } else if (tab === 'printshop') {
        const r = await api.get(`/internal-use?limit=500&date_from=${dateFrom}&date_to=${dateTo}`);
        setPrintshopData(r.data.data || []);
      }
    } finally { setLoading(false); }
  }, [tab, dateFrom, dateTo]);

  useEffect(() => { load(); }, [load]);

  const tabs: Array<{ key: ReportTab; label: string }> = [
    { key: 'sales',      label: t.reports_tab_sales },
    { key: 'products',   label: t.reports_tab_products },
    { key: 'inventory',  label: t.reports_tab_inventory },
    { key: 'cashiers',   label: t.reports_tab_cashiers },
    { key: 'printshop',  label: 'Print Shop Usage' },
  ];

  return (
    <PageContainer>
      <div className="page-header">
        <h1 className="page-title">{t.reports_title}</h1>
      </div>

      {/* Tab Bar */}
      <div className="flex gap-1 border-b border-surface-200 mb-4">
        {tabs.map((tb) => (
          <button key={tb.key} onClick={() => setTab(tb.key)}
            className={`px-5 py-2.5 text-sm font-medium border-b-2 transition-colors ${
              tab === tb.key ? 'border-primary-600 text-primary-600' : 'border-transparent text-surface-500 hover:text-surface-700'
            }`}>
            {tb.label}
          </button>
        ))}
      </div>

      {/* Date Range */}
      {tab !== 'inventory' && (
        <div className="flex flex-wrap items-end gap-3 mb-4">
          <div>
            <label className="label">{t.reports_from}</label>
            <input type="date" className="input" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} />
          </div>
          <div>
            <label className="label">{t.reports_to}</label>
            <input type="date" className="input" value={dateTo} onChange={(e) => setDateTo(e.target.value)} />
          </div>
          <div className="pt-5">
            <button onClick={load} className="btn-primary">{t.reports_load}</button>
          </div>

          {/* PDF download buttons */}
          {tab === 'sales' && salesData && (
            <div className="pt-5">
              <button onClick={() => downloadSalesPDF(salesData, dateFrom, dateTo)} className="btn-secondary">
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                    d="M12 10v6m0 0l-3-3m3 3l3-3M3 17V7a2 2 0 012-2h6l2 2h4a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
                </svg>
                Download PDF
              </button>
            </div>
          )}
          {tab === 'printshop' && printshopData.length > 0 && (
            <>
              <div className="pt-5">
                <button onClick={() => downloadPrintShopPDF(printshopData, dateFrom, dateTo)} className="btn-secondary">
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                      d="M12 10v6m0 0l-3-3m3 3l3-3M3 17V7a2 2 0 012-2h6l2 2h4a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
                  </svg>
                  Summary PDF
                </button>
              </div>
              <div className="pt-5">
                <button onClick={handleDetailedPDF} disabled={generatingPDF} className="btn-primary">
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                      d="M12 10v6m0 0l-3-3m3 3l3-3M3 17V7a2 2 0 012-2h6l2 2h4a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
                  </svg>
                  {generatingPDF ? 'Generating…' : 'Detailed PDF (with Items)'}
                </button>
              </div>
            </>
          )}
        </div>
      )}

      {loading ? <PageLoader /> : (
        <>
          {/* SALES */}
          {tab === 'sales' && salesData && (
            <>
              <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
                {[
                  [t.reports_total_sales,    fmt(salesData.summary?.total_revenue      || 0), 'text-primary-600'],
                  [t.reports_total_profit,   fmt(salesData.summary?.total_profit       || 0), 'text-emerald-600'],
                  [t.reports_transactions,   salesData.summary?.total_transactions     || 0,  ''],
                  [t.reports_cash_sales,     fmt(salesData.summary?.total_discounts    || 0), 'text-red-600'],
                ].map(([label, value, color], i) => (
                  <div key={i} className="stat-card">
                    <p className="stat-label">{label}</p>
                    <p className={`stat-value ${color}`}>{value}</p>
                  </div>
                ))}
              </div>
              <div className="card">
                <div className="table-wrapper">
                  <table className="table">
                    <thead>
                      <tr>
                        <th>{t.reports_col_date}</th>
                        <th className="text-right">{t.reports_col_transactions}</th>
                        <th className="text-right">{t.reports_col_revenue}</th>
                        <th className="text-right">{t.reports_col_profit}</th>
                        <th className="text-right">{t.reports_cash_sales}</th>
                      </tr>
                    </thead>
                    <tbody>
                      {(salesData.periods as Array<Record<string, unknown>>).map((row, i) => (
                        <tr key={i}>
                          <td>{new Date(String(row.period)).toLocaleDateString()}</td>
                          <td className="text-right">{String(row.transactions)}</td>
                          <td className="text-right font-mono font-semibold text-primary-600">{fmt(Number(row.revenue))}</td>
                          <td className="text-right font-mono text-emerald-600">{fmt(Number(row.profit))}</td>
                          <td className="text-right font-mono text-red-500">{fmt(Number(row.discounts))}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </>
          )}

          {/* PRODUCT SALES */}
          {tab === 'products' && (
            <div className="card">
              <div className="table-wrapper">
                <table className="table">
                  <thead>
                    <tr>
                      <th>{t.reports_col_product}</th>
                      <th>{t.category}</th>
                      <th className="text-right">{t.reports_col_qty}</th>
                      <th className="text-right">{t.reports_col_revenue}</th>
                      <th className="text-right">{t.reports_col_cost}</th>
                      <th className="text-right">{t.reports_col_profit}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(productsData as Array<Record<string, unknown>>).map((p, i) => (
                      <tr key={i}>
                        <td className="font-medium">{String(p.product_name)}</td>
                        <td>{String(p.category_name || '—')}</td>
                        <td className="text-right font-mono">{Number(p.qty_sold).toFixed(2)}</td>
                        <td className="text-right font-mono text-primary-600">{fmt(Number(p.revenue))}</td>
                        <td className="text-right font-mono text-surface-500">{fmt(Number(p.cost))}</td>
                        <td className="text-right font-mono text-emerald-600">{fmt(Number(p.profit))}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* INVENTORY */}
          {tab === 'inventory' && (
            <div className="card">
              <div className="px-4 py-3 border-b border-surface-200 flex items-center justify-between">
                <span className="text-sm font-medium text-surface-700">
                  Total Stock Value:{' '}
                  <span className="font-bold text-primary-600">
                    {fmt((inventoryData as Array<Record<string, number>>).reduce((s, p) => s + (Number(p.stock_value) || 0), 0))}
                  </span>
                </span>
                <span className="text-sm text-surface-500">{inventoryData.length} products</span>
              </div>
              <div className="table-wrapper">
                <table className="table">
                  <thead>
                    <tr>
                      <th>{t.reports_col_product}</th>
                      <th>SKU</th>
                      <th>{t.category}</th>
                      <th className="text-right">{t.reports_col_stock}</th>
                      <th className="text-right">{t.inventory_col_avg_cost}</th>
                      <th className="text-right">{t.reports_col_stock_value}</th>
                      <th>{t.status}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(inventoryData as Array<Record<string, unknown>>).map((p, i) => (
                      <tr key={i}>
                        <td className="font-medium">{String(p.name)}</td>
                        <td className="font-mono text-xs">{String(p.sku)}</td>
                        <td>{String(p.category_name || '—')}</td>
                        <td className="text-right font-mono">{Number(p.current_stock).toFixed(2)}</td>
                        <td className="text-right font-mono">LKR {Number(p.avg_cost).toFixed(4)}</td>
                        <td className="text-right font-mono font-semibold">LKR {Number(p.stock_value).toFixed(2)}</td>
                        <td>
                          <span className={`badge ${p.is_low_stock ? 'badge-red' : 'badge-green'}`}>
                            {p.is_low_stock ? t.inventory_low_stock : t.inventory_ok}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* CASHIERS */}
          {tab === 'cashiers' && (
            <div className="card">
              <div className="table-wrapper">
                <table className="table">
                  <thead>
                    <tr>
                      <th>{t.reports_col_name}</th>
                      <th className="text-right">{t.reports_col_transactions}</th>
                      <th className="text-right">{t.reports_col_revenue}</th>
                      <th className="text-right">{t.reports_col_profit}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(cashiersData as Array<Record<string, unknown>>).map((c, i) => (
                      <tr key={i}>
                        <td className="font-medium">{String(c.cashier_name)}</td>
                        <td className="text-right">{String(c.transactions)}</td>
                        <td className="text-right font-mono text-primary-600">{fmt(Number(c.revenue))}</td>
                        <td className="text-right font-mono text-emerald-600">{fmt(Number(c.profit))}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* PRINT SHOP USAGE */}
          {tab === 'printshop' && (
            <>
              {printshopData.length > 0 && (
                <div className="grid grid-cols-2 lg:grid-cols-3 gap-4 mb-4">
                  <div className="stat-card">
                    <p className="stat-label">Total Records</p>
                    <p className="stat-value">{printshopData.length}</p>
                  </div>
                  <div className="stat-card">
                    <p className="stat-label">Total Stock Cost Used</p>
                    <p className="stat-value text-primary-600">
                      {fmt(printshopData.reduce((s, r) => s + Number(r.total_cost || 0), 0))}
                    </p>
                  </div>
                </div>
              )}
              <div className="card">
                <div className="table-wrapper">
                  <table className="table">
                    <thead>
                      <tr>
                        <th>Reference</th>
                        <th>Purpose</th>
                        <th className="text-right">Total Cost</th>
                        <th>By</th>
                        <th>Date</th>
                      </tr>
                    </thead>
                    <tbody>
                      {printshopData.length === 0 ? (
                        <tr><td colSpan={5} className="text-center py-8 text-surface-400">No print shop usage in this period</td></tr>
                      ) : printshopData.map((rec, i) => (
                        <tr key={i}>
                          <td className="font-mono text-primary-600 text-xs">{String(rec.reference_number)}</td>
                          <td>{String(rec.purpose || '—')}</td>
                          <td className="text-right font-mono font-semibold">{fmt(Number(rec.total_cost || 0))}</td>
                          <td className="text-surface-500">{String(rec.created_by_name || '')}</td>
                          <td className="text-xs text-surface-400">
                            {new Date(String(rec.created_at)).toLocaleDateString()}{' '}
                            {new Date(String(rec.created_at)).toLocaleTimeString()}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </>
          )}
        </>
      )}
    </PageContainer>
  );
}
